"""
Prepare raw LUDB v1.0.1 for the existing ecgclip classification pipeline.

The script:
  1. reads LUDB's official ludb.csv metadata;
  2. derives broad record-level multi-label categories;
  3. creates reproducible folds 1..10;
  4. writes WORK_DIR/labels.csv in the same shape expected by ecgclip; and
  5. renders each 12-lead WFDB record to WORK_DIR/images/<id>.png.

Usage:
    ECG_DATASET=ludb DATA_DIR=/path/to/ludb/1.0.1 python prepare_ludb.py
    ECG_DATASET=ludb DATA_DIR=/path/to/ludb/1.0.1 python prepare_ludb.py --limit 40
    ECG_DATASET=ludb DATA_DIR=/path/to/ludb/1.0.1 python prepare_ludb.py --no-render
"""
from __future__ import annotations

import argparse
import os
import warnings
from typing import Iterable

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from tqdm import tqdm

import config as C


LUDb_TEXT_COLUMNS = [
    "Rhythms",
    "Electric axis of the heart",
    "Conduction abnormalities",
    "Extrasystolies",
    "Hypertrophies",
    "Cardiac pacing",
    "Ischemia",
    "Non-specific repolarization abnormalities",
    "Other states",
]

# These rhythm descriptions are treated as sinus-family rhythms. Arrhythmia is
# positive when another rhythm is listed or an extrasystole field is present.
SINUS_FAMILY_RHYTHMS = {
    "Sinus rhythm",
    "Sinus bradycardia",
    "Sinus tachycardia",
    "Sinus arrhythmia",
    "Irregular sinus rhythm",
}


def clean_text(value: object) -> str:
    """Normalize LUDB cells while preserving multiple newline-separated items."""
    if pd.isna(value):
        return ""
    lines = [part.strip() for part in str(value).replace("\r", "\n").split("\n")]
    return "\n".join(part for part in lines if part)


def has_text(series: pd.Series) -> pd.Series:
    return series.fillna("").astype(str).str.strip().ne("")


def derive_label_frame(df: pd.DataFrame) -> pd.DataFrame:
    """Create broad multi-label targets from official LUDB metadata columns.

    Mapping used by this adapter:
      ARR       = non-sinus-family rhythm OR any extrasystole
      CD        = conduction abnormality OR cardiac pacing
      HYP       = any hypertrophy/overload entry
      ISCHEMIA  = any ischemia/STEMI/scar/NSTEMI entry
      REPOL     = non-specific repolarization abnormality OR early repolarization
      NORM      = none of the five abnormal categories above

    This mapping is intentionally explicit and should be reported as a derived
    task definition rather than an official LUDB label ontology.
    """
    rhythm = df["Rhythms"].fillna("").astype(str).str.strip()

    labels = pd.DataFrame(index=df.index)
    labels["ARR"] = (~rhythm.isin(SINUS_FAMILY_RHYTHMS)) | has_text(
        df["Extrasystolies"]
    )
    labels["CD"] = has_text(df["Conduction abnormalities"]) | has_text(
        df["Cardiac pacing"]
    )
    labels["HYP"] = has_text(df["Hypertrophies"])
    labels["ISCHEMIA"] = has_text(df["Ischemia"])
    labels["REPOL"] = has_text(
        df["Non-specific repolarization abnormalities"]
    ) | has_text(df["Other states"])
    labels["NORM"] = ~labels[["ARR", "CD", "HYP", "ISCHEMIA", "REPOL"]].any(
        axis=1
    )

    missing = set(C.CLASSES) - set(labels.columns)
    if missing:
        raise ValueError(
            f"config.CLASSES contains labels not generated by prepare_ludb.py: {missing}"
        )
    return labels[C.CLASSES].astype(np.float32)


def assign_folds(y: np.ndarray, seed: int = C.SEED) -> np.ndarray:
    """Return fold numbers 1..10, preferring iterative multi-label stratification."""
    if len(y) < 10:
        raise ValueError("At least 10 LUDB records are required to create 10 folds")

    folds = np.zeros(len(y), dtype=np.int64)
    try:
        from iterstrat.ml_stratifiers import MultilabelStratifiedKFold

        splitter: Iterable[tuple[np.ndarray, np.ndarray]] = (
            MultilabelStratifiedKFold(
                n_splits=10,
                shuffle=True,
                random_state=seed,
            ).split(np.zeros((len(y), 1), dtype=np.float32), y)
        )
    except ImportError:
        warnings.warn(
            "iterative-stratification is not installed; falling back to KFold. "
            "Install it for better multi-label class balance: "
            "pip install iterative-stratification",
            RuntimeWarning,
        )
        splitter = KFold(n_splits=10, shuffle=True, random_state=seed).split(y)

    for fold_number, (_, held_out_indices) in enumerate(splitter, start=1):
        folds[held_out_indices] = fold_number

    if set(folds.tolist()) != set(range(1, 11)):
        raise RuntimeError("Failed to assign all LUDB folds 1..10")
    return folds


def build_report(row: pd.Series) -> str:
    """Build an English text caption from LUDB's expert metadata."""
    parts: list[str] = []
    field_names = {
        "Rhythms": "rhythm",
        "Electric axis of the heart": "axis",
        "Conduction abnormalities": "conduction",
        "Extrasystolies": "ectopy",
        "Hypertrophies": "hypertrophy/overload",
        "Cardiac pacing": "pacing",
        "Ischemia": "ischemia/scar",
        "Non-specific repolarization abnormalities": "repolarization",
        "Other states": "other",
    }
    for column in LUDb_TEXT_COLUMNS:
        value = clean_text(row[column]).replace("\n", "; ")
        if value:
            parts.append(f"{field_names[column]}: {value}")
    return ". ".join(parts) if parts else "12-lead electrocardiogram"


def load_metadata(data_dir: str = C.DATA_DIR) -> pd.DataFrame:
    csv_path = os.path.join(data_dir, "ludb.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Could not find {csv_path}. DATA_DIR must be the LUDB version root "
            "containing ludb.csv and the data/ directory."
        )

    df = pd.read_csv(csv_path)
    required = {"ID", *LUDb_TEXT_COLUMNS}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"ludb.csv is missing required columns: {sorted(missing)}")

    for column in df.columns:
        if df[column].dtype == object:
            df[column] = df[column].map(clean_text)

    df["ID"] = pd.to_numeric(df["ID"], errors="raise").astype(int)
    df = df.set_index("ID")
    df.index.name = "ecg_id"
    df["record"] = [os.path.join("data", str(record_id)) for record_id in df.index]

    label_frame = derive_label_frame(df)
    df["strat_fold"] = assign_folds(label_frame.to_numpy())
    df["superclasses"] = label_frame.apply(
        lambda row: [name for name in C.CLASSES if row[name] > 0.5], axis=1
    )
    df["report"] = df.apply(build_report, axis=1)
    for class_name in C.CLASSES:
        df[class_name] = label_frame[class_name]
    return df


def split_indices(df: pd.DataFrame) -> tuple[pd.Series, pd.Series, pd.Series]:
    train = df.strat_fold.isin(C.TRAIN_FOLDS)
    val = df.strat_fold.eq(C.VAL_FOLD)
    test = df.strat_fold.eq(C.TEST_FOLD)
    return train, val, test


def image_path_for(ecg_id: int) -> str:
    return os.path.join(C.IMG_DIR, f"{int(ecg_id):05d}.png")


def render_all(df: pd.DataFrame) -> None:
    # Lazy import keeps --no-render usable in lightweight metadata environments.
    from ecg_to_image import load_signal, render_to_file

    for ecg_id, row in tqdm(df.iterrows(), total=len(df), desc="Rendering LUDB ECGs"):
        output_path = image_path_for(int(ecg_id))
        if os.path.exists(output_path):
            continue

        signal, fields = load_signal(C.DATA_DIR, row[C.FILENAME_COL])
        if signal.ndim != 2 or signal.shape[1] != 12:
            raise ValueError(
                f"LUDB record {ecg_id} has shape {signal.shape}; expected (samples, 12)"
            )
        fs = float(fields.get("fs", C.SAMPLING_RATE))
        render_to_file(signal, fs, output_path)


def save_labels(df: pd.DataFrame) -> str:
    columns = [C.FILENAME_COL, "strat_fold", "report", "superclasses", *C.CLASSES]
    metadata = df[columns].copy()
    metadata["superclasses"] = metadata["superclasses"].map("|".join)
    output_path = os.path.join(C.WORK_DIR, "labels.csv")
    metadata.to_csv(output_path)
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="use only the first N records after fold assignment (smoke test)",
    )
    parser.add_argument(
        "--no-render",
        action="store_true",
        help="write labels.csv without producing PNG files",
    )
    args = parser.parse_args()

    if C.DATASET != "ludb":
        raise RuntimeError(
            "prepare_ludb.py requires ECG_DATASET=ludb. "
            "Example: ECG_DATASET=ludb DATA_DIR=/path/to/ludb/1.0.1 "
            "python prepare_ludb.py"
        )

    print(f"Loading LUDB metadata from {C.DATA_DIR}")
    df = load_metadata()
    if args.limit is not None:
        if args.limit <= 0:
            raise ValueError("--limit must be positive")
        df = df.iloc[: args.limit].copy()

    train, val, test = split_indices(df)
    print(
        f"Records: {len(df)} | train {int(train.sum())} | "
        f"val {int(val.sum())} | test {int(test.sum())}"
    )
    for class_name in C.CLASSES:
        print(f"  {class_name:9s}: {int(df[class_name].sum())} positive")

    labels_path = save_labels(df)
    print(f"Saved labels -> {labels_path}")

    if not args.no_render:
        render_all(df)
        print(f"Images -> {C.IMG_DIR}")


if __name__ == "__main__":
    main()
